apiVersion: v1
kind: Pod
metadata:
  name: pod-kafka-consumer
  labels:
    app: microservicek
spec:
    containers:
      - name: micros
        image: cristiank/kafka-consumer-nodejs:1.1
        env:
           - name: KAFKA_BROKER
             value: kafka-broker-service:9092